// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fysscaunkipboyuqodma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5c3NjYXVua2lwYm95dXFvZG1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NDE5MjcsImV4cCI6MjA2NTAxNzkyN30.8NO6rIm988vHEcOB-M86BGF2I-fctyDRWBrLW61elJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);